// <auto-generated />
using AppDotacion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDotacion.Migrations
{
    [DbContext(typeof(AppDotacionContext))]
    partial class AppDotacionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppDotacion.Models.Dotacion", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<string>("Agente")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Agente");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Area");

                    b.Property<string>("AreaGestion")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AreaGestion");

                    b.Property<string>("CARGO")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CARGO");

                    b.Property<string>("Clasifica_Cargo")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Clasifica_Cargo");

                    b.Property<byte?>("Contrato")
                        .HasColumnType("tinyint")
                        .HasColumnName("Contrato");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Correo");

                    b.Property<byte?>("DV")
                        .HasColumnType("tinyint")
                        .HasColumnName("DV");

                    b.Property<int?>("Fecha_Baja")
                        .HasColumnType("int")
                        .HasColumnName("Fecha_Baja");

                    b.Property<int?>("Fecha_Ingreso")
                        .HasColumnType("int")
                        .HasColumnName("Fecha_Ingreso");

                    b.Property<int?>("N_Personal")
                        .HasColumnType("int")
                        .HasColumnName("N_Personal");

                    b.Property<string>("Nombre_Call_Center")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Call_Center");

                    b.Property<string>("Nombre_Jefatura")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Jefatura");

                    b.Property<string>("Pais_Call_Center")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pais_Call_Center");

                    b.Property<string>("Rut_DNI")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rut_DNI");

                    b.Property<string>("Rut_DNI2")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rut_DNI2");

                    b.Property<string>("Rut_Ficticio")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rut_Ficticio");

                    b.Property<string>("Servicio")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Servicio");

                    b.Property<string>("Tipos_de_agente")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipos_de_agente");

                    b.Property<string>("Usuarios_RcWeb")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuarios_RcWeb");

                    b.HasKey("ID");

                    b.ToTable("Dotaciones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
